# Site settings
title: Vera Plugin for Ecobee
description: > # this means to ignore newlines until "baseurl:"
  Monitor and control your Ecobee thermostat(s) through your Vera] home controller.
baseurl: "/vera-ecobee-thermostat/" # the subpath of your site, e.g. /blog/
url: "http://watou.github.io" # the base hostname & protocol for your site
twitter_username: jcocula
github_username:  watou

# Build settings
markdown: kramdown
